### ISSUE TITLE
check Icon and Timed Button

### ISSUE THREAD

**Issue by lehmi11** [ost-cas-fee-adv-23-24/design-system-component-library-football-fanatics#17]
check if the current button implementation can create icon and timed buttons

**Comment by bladicito** [comment]
timedButton implemented used base button

**Comment by lehmi11** [comment]
toggle was implemented in https://github.com/ost-cas-fee-adv-23-24/design-system-component-library-football-fanatics/commit/cc55e42e52422a8dbad4ca15c4acb61356a6bb22
icon was implemented in https://github.com/ost-cas-fee-adv-23-24/design-system-component-library-football-fanatics/commit/43093dd955adb74e8c5ab5e818e481c84e5154d1
